// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cayfkqdoormcjyfzlfbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNheWZrcWRvb3JtY2p5ZnpsZmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjY5NDksImV4cCI6MjA2NTkwMjk0OX0.7qHDilyBlusMDOJhOkrBsNd0asufnU9fNlSKAjT8q4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);